<div class="text-right m-b-md">
    <a href="<?= url() ?>" type="button" class="btn btn-warning btn-lg panel-btn-right">
        <i class="fa fa-chevron-left"></i>
        Voltar
    </a>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <form>
            <div class="panel panel-default">

                <div class="panel-content">

                    <div class="modal-body">
                        <div class="row">

                            <div class="col-md-3 col-sm-12 col-xs-12">

                                <div class="form-group">

                                    <label>Status</label><span class="pointer" data-toggle="popover" data-trigger="hover" data-content="Selecione um status." data-original-title="" title="">[<i class="fa fa-question"></i>]</span>
                                    <select name="destaque" class="form-control">
                                        <option value="1">Ativada</option>
                                        <option value="0">Desativada</option>
                                    </select>

                                </div>

                            </div>

                            <div class="col-md-9 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label class="">Título</label><span class="pointer" data-toggle="popover" data-trigger="hover" data-content="Ditie um título para a licença." data-original-title="" title="">[<i class="fa fa-question"></i>]</span>
                                    <input type="text" name="titulo" class="form-control text">
                                </div>
                            </div>  
                            
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="form-group">
                                    <label class="">Créditos</label><span class="pointer" data-toggle="popover" data-trigger="hover" data-content="Ditie o valor dos créditos." data-original-title="" title="">[<i class="fa fa-question"></i>]</span>
                                    <input type="text" name="creditos" class="form-control text">
                                </div>
                            </div>
                            
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="form-group">
                                    <label class="">Adesão</label><span class="pointer" data-toggle="popover" data-trigger="hover" data-content="Ditie o valor da adesão." data-original-title="" title="">[<i class="fa fa-question"></i>]</span>
                                    <input type="text" name="adesao" class="form-control text">
                                </div>
                            </div>
                            
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="form-group">
                                    <label class="">Cartão</label><span class="pointer" data-toggle="popover" data-trigger="hover" data-content="Digite o valor do cartão." data-original-title="" title="">[<i class="fa fa-question"></i>]</span>
                                    <input type="text" name="cartao" class="form-control text">
                                </div>
                            </div>
                            
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="form-group">
                                    <label class="">Mensalidade</label><span class="pointer" data-toggle="popover" data-trigger="hover" data-content="Digite o valor da mensalidade." data-original-title="" title="">[<i class="fa fa-question"></i>]</span>
                                    <input type="text" name="mensalidade" class="form-control text">
                                </div>
                            </div>
                            
                            <?php for ($i = 1; $i <= 5; $i++) : ?>

                                <div class="col-md-4 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                        <label class="">Pontos <?= $i ?>º nível</label><span class="pointer" data-toggle="popover" data-trigger="hover" data-content="Digite os pontos para esse nível." data-original-title="" title="">[<i class="fa fa-question"></i>]</span>
                                        <input type="text" name="ponto<?= $i ?>" class="form-control text">
                                    </div>
                                </div>

                            <?php endfor; ?>

                            <div class="col-md-4 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label class="">Cor(Hexadecimal)</label><span class="pointer" data-toggle="popover" data-trigger="hover" data-content="Digite o valor da cor hexadecimal. Ex: #333" data-original-title="" title="">[<i class="fa fa-question"></i>]</span>
                                    <input type="text" name="ponto<?= $i ?>" class="form-control text">
                                </div>
                            </div>


                        </div>
                    </div>
                </div>

                <div class="text-right panel-footer">

                    <div class="row">
                        <div class="col-xs-6 text-left">
                            <label for="" class="btn-success btn btn-inputfile">
                                <span><i class="fa fa-image"></i> Imagem <span></span></span>
                                <input type="file" name="upimagens" id="imagem" accept="image/*">
                            </label>
                        </div>
                        <div class="col-xs-6 text-right">
                            <button class="btn btn-danger" type="reset">
                                <i class="fa fa-eraser"></i>
                                Limpar
                            </button>

                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-save"></i>
                                Salvar
                            </button>
                        </div>
                    </div>

                </div>

            </div>
        </form>
    </div>
</div>

