<div class="row">
    <div class="col-md-12">
        <form onsubmit="javascript: return false;">
            <div class="panel panel-default">
                <div class="panel-body p-b-10">
                    <div class="row">
                        <div class="form-group col-md-3 col-xs-12">
                            <label>Status</label><span class="pointer" data-toggle="popover" data-trigger="hover" data-content="Selecione um status para busca" data-original-title="" title="">[<i class="fa fa-question"></i>]</span>
                            <select name="destaque" class="form-control">
                                <option value="1">Ativada</option>
                                <option value="0">Desativada</option>
                            </select>
                        </div>
                        <div class="form-group col-md-3 col-xs-6">
                            <label>Data de cadastro</label><span class="pointer" data-toggle="popover" data-trigger="hover" data-content="Digite ou selecione uma data de cadastro para a busca." data-original-title="" title="">[<i class="fa fa-question"></i>]</span>
                            <input type="date" name="data-cadastro" class="form-control text-center">
                        </div>
                        <div class="form-group col-md-6 col-xs-12">
                            <label>Título</label><span class="pointer" data-toggle="popover" data-trigger="hover" data-content="Digite um título para a busca." data-original-title="" title="">[<i class="fa fa-question"></i>]</span>
                            <input name="search" type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="text-right panel-footer clearfix">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-search"></i> Buscar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-12">

        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th width="140">Data de cadastro</th>
                    <th width="160">Título</th>
                    <th width="60">Crédito</th>
                    <th width="60">Adesão</th>
                    <th width="60">Cartão</th>
                    <th width="60">Mensalidade</th>
                    <th width="60">Status</th>
                    <th width="60"></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="text-center" style="vertical-align: middle">15/06/2017</td>
                    <td style="vertical-align: middle">Título</td>
                    <td style="vertical-align: middle" class="text-center">R$ 0,00</td>
                    <td style="vertical-align: middle" class="text-center">R$ 0,00</td>
                    <td style="vertical-align: middle" class="text-center">R$ 0,00</td>
                    <td style="vertical-align: middle" class="text-center">R$ 0,00</td>
                    <td style="vertical-align: middle" class="text-center">Ativado</td>
                    <td style="vertical-align: middle" class="text-center">
                        <div class="btn-group">
                            <div class="btn btn-default" ><i class="fa fa-eye"></i></div>
                            <a class="btn btn-default" href="#">
                                <i class="fa fa-edit"></i>
                            </a>
                            <div class="btn btn-danger" ><i class="fa fa-remove"></i></div>
                        </div>
                    </td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="12">Exibindo de 1 até 5 de 5 registros</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
