<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12 ">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h4 class="panel-title">Apostas em Aberto</h4>
                <div class="pull-right m-t-minus-9">
                    <div class="btn btn-default"><i class="fa fa-print"></i> Imprimir</div>
                </div>
            </div>
            <div class="panel-body">
                <form method="post" class="page-form-search">
                    <div class="col-xs-6">
                        <label>DT/Início</label>
                        <input type="date" name="dataInicial" class="form-control" />
                    </div>
                    <div class="col-xs-6">
                        <label>DT/Final</label>
                        <input type="date" name="dataFinal" class="form-control" />
                    </div>
                </form>
            </div>
            <div class="panel-body page-container panel-table"></div>
        </div>
    </div>
</div>