<script>
    $(function () {
        var page = $("<div />").adminPage({
            controller: 'apostas/minhas',
            formSearch: '.page-form-search',
            container: '.page-container',
            deleteAction: url('apostas/aposta/excluir'),
        });
    });
</script>

{% include 'admin/apostas/modal-jogos.twig' %}

<form method="post" class="page-form-search" onsubmit="javascript:return false;">
    <div class="panel panel-default">
        <div class="panel-heading clearfix">
            <h4 class="panel-title">Lista de Apostas</h4>
        </div>
        <div class="panel-body p-b-10">
            <div class="row">
                <div class="form-group col-sm-4 col-xs-12">
                    <label>Comprovante</label>
                    <input type="number" class="form-control"/>
                </div>
                <div class="form-group col-sm-4 col-xs-6">
                    <label>DT/Início</label>
                    <input type="date" class="form-control" name="dataInicial"/>
                </div>
                <div class="form-group col-sm-4 col-xs-6">
                    <label>DT/Fim</label>
                    <input type="date" class="form-control" name="dataFinal"/>
                </div>
            </div>
        </div>
        <div class="panel-footer">

            <div class="text-right">
                <button type="submit" class="btn btn-info">
                    <i class="fa fa-search"></i> Pesquisar
                </button>
            </div>
        </div>
    </div>
</form>

<div class="panel-body page-container panel-table"></div>

<div class="m-t-10">
    <span class="text-info m-r-10"><i class="fa fa-circle"></i> Ganhou a aposta</span>
    <span class="text-danger m-r-10"><i class="fa fa-circle"></i> Perdeu a aposta</span>
    <span class="m-r-10"><i class="fa fa-circle"></i> Aguardando o jogo terminar</span>
    <span class="text-lilas m-r-10"><i class="fa fa-circle"></i> Aposta cancelada</span>
</div>